export const FETCH_FAQS = 'FETCH_FAQS';

//movies
export const FETCH_MOVIES = 'FETCH_MOVIES';
export const SELECT_MOVIE = 'SELECT_MOVIE';
export const FETCH_MOVIE_GENRES = 'FETCH_MOVIE_GENRES';
export const FILTER_MOVIES_BY_GENRE = 'FILTER_MOVIES';
export const FILTER_MOVIES_BY_NAME = 'FILTER_MOVIES_BY_NAME';
export const FETCH_MOVIE_TRAILER = 'FETCH_MOVIE_TRAILER';
export const TOGGLE_MOVIE_PLAYER = 'TOGGLE_MOVIE_PLAYER';
export const FETCH_MORE_MOVIES = 'FETCH_MORE_MOVIES';
export const UPDATE_MOVIE_PAGE = 'UPDATE_MOVIE_PAGE';
export const RESET_MOVIE_FILTERS = 'RESET_MOVIE_FILTERS';
export const DELETE_MOVIE = 'DELETE_MOVIE';

//tv shows
export const FETCH_SHOWS = 'FETCH_SHOWS';
export const SELECT_SHOW = 'SELECT_SHOW';
export const FETCH_SHOW_GENRES = 'FETCH_SHOW_GENRES';
export const FILTER_SHOWS_BY_GENRE = 'FILTER_SHOWS';
export const FILTER_SHOWS_BY_NAME = 'FILTER_SHOWS_BY_NAME';
export const FETCH_SHOW_TRAILER = 'FETCH_SHOW_TRAILER';
export const TOGGLE_SHOW_PLAYER = 'TOGGLE_SHOW_PLAYER';
export const FETCH_MORE_SHOWS = 'FETCH_MORE_SHOWS';
export const UPDATE_SHOW_PAGE = 'UPDATE_SHOW_PAGE';
export const RESET_SHOW_FILTERS = 'RESET_SHOW_FILTERS';
export const DELETE_SHOW = 'DELETE_SHOW';


//user actions
export const GET_USERS = 'GET_USERS';
export const DELETE_USER = 'DELETE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const REGISTER = 'REGISTER';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

//App-wide actions
export const SET_LOADING = 'SET_LOADING';



