export const FETCH_FAQS = 'FETCH_FAQS';

//movies
export const FETCH_MOVIES = 'FETCH_MOVIES';
export const SELECT_MOVIE = 'SELECT_MOVIE';
export const FETCH_MOVIE_GENRES = 'FETCH_MOVIE_GENRES';
export const FILTER_MOVIES_BY_GENRE = 'FILTER_MOVIES';
export const FILTER_MOVIES_BY_NAME = 'FILTER_MOVIES_BY_NAME';
export const FETCH_MOVIE_TRAILER = 'FETCH_MOVIE_TRAILER';
export const TOGGLE_MOVIE_PLAYER = 'TOGGLE_MOVIE_PLAYER';

//tv shows
export const FETCH_SHOWS = 'FETCH_SHOWS';
export const SELECT_SHOW = 'SELECT_SHOW';
export const FETCH_SHOW_GENRES = 'FETCH_SHOW_GENRES';
export const FILTER_SHOWS_BY_GENRE = 'FILTER_SHOWS';
export const FILTER_SHOWS_BY_NAME = 'FILTER_SHOWS_BY_NAME';
export const FETCH_SHOW_TRAILER = 'FETCH_SHOW_TRAILER';
export const TOGGLE_SHOW_PLAYER = 'TOGGLE_SHOW_PLAYER';


//user actions

export const REGISTER = 'REGISTER'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'



