export const FETCH_FAQS = 'FETCH_FAQS';

//movies
export const FETCH_MOVIES = 'FETCH_MOVIES';
export const SELECT_MOVIE = 'SELECT_MOVIE';
export const FETCH_MOVIE_GENRES = 'FETCH_MOVIE_GENRES';
export const FILTER_MOVIES_BY_GENRE = 'FILTER_MOVIES';
export const FILTER_MOVIES_BY_NAME = 'FILTER_MOVIES_BY_NAME';

//tv shows
export const FETCH_SHOWS = 'FETCH_SHOWS';
export const SELECT_SHOW = 'SELECT_SHOW';
export const FETCH_SHOW_GENRES = 'FETCH_SHOW_GENRES';
export const FILTER_SHOWS_BY_GENRE = 'FILTER_SHOWS';
export const FILTER_SHOWS_BY_NAME = 'FILTER_SHOWS_BY_NAME';



